/**
 * Auto-generated bone registry by Boneyard
 * This file is automatically generated when you run: npm run dev or npm run build
 * 
 * To regenerate bones from your UI:
 * 1. Run: npm run dev (bones auto-capture on HMR updates)
 * 2. Or manually: npx boneyard-js build --watch
 * 
 * Bones are captured from <Skeleton name="..."> components in your pages
 */

import { registerBones } from 'boneyard-js/react';

// Bones will be auto-registered here by the build process
// No manual configuration needed!

export {};
